spring.application.name=provider-content-service-pfe
spring.config.import=optional:configserver:http://localhost:8888
public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApQ55hNwvW8Sf7lOKRLcAwNSvs2TDUpu+LdYpJeCic++RQpTeUpalwrqd9mvUvTSOVlVwkjRwUikp6p101iYOGNWS4fC+ktf/75CXVmeRdOplzGz5yuDfMLlv1stk5bEYcW02aR5SZBBn36r67R/LWlmHvPgKzGe3AOvOkLZR7ByoN6Fg2udj5f5HQ2tdx148X+2U2rIeyTbnygd3Wmpky7TM/kWlwfKuZnHO3sHw595lOCgyy9JhIGvz8BQEZUUmJklWrVlPL1Y355NVzFfWnccOGTFYigutlpegIrHmL3wZZMih0Ol5gpCC3xUyydeYEzh07/+kQglTPColLUvc3wIDAQAB

